### ISSUE TITLE
Update to latest version of duckdb

### ISSUE THREAD

**Issue by mhkeller** [uwdata/mosaic#207]
As a general note, I'm not sure if this is a bug in Mosaic, Electron or DuckDB but I made a reproduction here: https://github.com/mhkeller/duckdb-electron-mosaic-crash

When trying to start up the data server from Electron, it crashes with a `SIGSEGV` error. The line that triggers it is the call to`vg.plot(args)`. If you launch the server via `child_process.exec`, it works. I'm not sure how to get more info on this so posting here in case anyone has any ideas. 

I'm loading `@uwdata/mosaic-duckdb` via an `await import` command because Electron doesn't support CommonJS but maybe that esm/commonjs mismatch is still causing problems. 

It could also be likely that this has nothing to do with Mosaic and is a DuckDB/Electron problem. If there is a way to isolate better which DuckDB commands are being executed, that would be helpful to narrow down the culprit.

Thanks for any help.

edit: for what it's worth, the top lines in the macos crash report are below. My inclination is this is a duckdb bug and it would be helpful to figure out what commands mosaic is sending to duckdb that are causing the crash.

```
0   duckdb.node                   	       0x16757b2ff node_duckdb::RunPreparedTask::Callback() + 3295
1   duckdb.node                   	       0x167565943 node_duckdb::Task::DoCallback() + 67
2   duckdb.node                   	       0x1675618f7 node_duckdb::TaskCompleteCallback(napi_env__*, napi_status, void*) + 167
```

**Comment by mhkeller** [comment]
It looks like this is fixed by updating to the latest version of duckdb, 0.9.1

Adding this to package.json fixes it

```
  "overrides": {
  	"@uwdata/mosaic-duckdb": {
  		"duckdb": "^0.9.1"
  	}
  }
```

**Comment by jheer** [comment]
We will update DuckDB when a non-broken node.js client + arrow extension is released. Currently the client will crash with valid queries due to issues in the arrow extension, which as of v9.2 still persist.

**Comment by mhkeller** [comment]
Closing because latest release updates to 0.10 and switches to using a python server instead of this problematic arrow extension.
